### PR TITLE
Refactor the "Data was entered by humans" section

### PR DESCRIPTION
**Pull request by StevenBlack**
This paragraph is now shorter and less circuitous.

Original version claimed "There is no worse way to screw up data than to let a single human type it in".  This is false.  Data variability increases significantly with the number of people entering data in free form fields.  The dog-breed example provided says so.

Also the claim that "Even with the best tools available, data this messy can't be saved" is overblown.  The example, as described, isn't difficult since the data domain (dog breeds) is finite.

It might take time and effort, but finite domain data cleansing is rarely impossible.  It depends, and it's not proper to generalize so dramatically here.

So this new version is softer.

### CODE REVIEW

**Comment by onyxfish** [comment]
Hi Steven, I appreciate your effort, but I disagree with your assessment here. When I refer to a single human typing it in, I refer to not having a validation step, not the number of independent contributors. (I address that case in the "human editors" section.)

To your other critique, I actually worked with the data I refer to and I promise it could not be saved. The domain (dog breeds) when entered by humans is not finite. What is a "Chihuahua/Terrier mix" for instance? I choose to generalize dramatically because I want to convey the worst case scenario and thus why reporters should be especially leery of this sort of problem.

More to the point, I think perhaps your critique might have been more graciously framed as a serious of questions, rather than presuming to rewrite the section to your own preferences.

**Comment by StevenBlack** [comment]
You seem vexed.  I'm sorry, but I thought I was working on a very weak paragraph.

To clarify: I have 30+ years experience doing this sort of thing, not just in straightforward contexts, but usually with data consolidated from many countries.  I know what I'm talking about here.

The paragraph as written is ridiculous, in my experience.  My initial thought was, the writing is atrocious.  But upon inspection what it says is misleading at best, patently false at worse.

Regardless.  Normalizing the spelling of individual dog breeds within strings is trivial because I work with people who fix these sorts of things every day.

The normalizing of mixed breeds is probably inadvisable, but that's not what I said.  I said the domain is finite because the components of the string (breeds) is finite and, ghowever you intermix these strings, cleaning-up this data to a sufficient number of "nines" for the budget / time / requirements is *trivial*.

**You** might not be able to make it perfect, but from there saying `Even with the best tools available, data this messy can't be saved` is just some guy with insufficient will, or budget, or experience, or understanding.  This is drawing broad conclusions from defeat by a trivial mechanical task.

I'm sorry but the phrase `There is no worse way to screw up data than to let a single human type it in` is just idiotic.  

You should strive for better.

**Comment by onyxfish** [comment]
Mr. Black, I appreciate you have strong opinions on this subject, however your approach to sharing them is arrogant and off-putting. I hope you would take a step back from your comments and recognize that you are not my editor, nor did I solicit your feedback. I welcome constructive criticism, however your comments seem to presume I am incompetent. I would normally simply ignore them, however, I encounter this attitude nowhere more frequently then on Github and I feel obligated to call it out in the hopes you might recognize how you are coming across and strive, as you say, to do better.

We have a lovely portmanteau for this behavior, which I would [encourage you to familiarize yourself with](https://en.wikipedia.org/wiki/Mansplaining).

**Comment by StevenBlack** [comment]
@danmichaelo no worries.  I submitted an improvement in good faith because, at the time, I genuinely cared.   

In the process,  I learned that @onyxfish is an arrogant asshole.  I've long since moved-on  😄.

**Pull request closed without merging**
